name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-revan:latest .

      - name: Push da imagem para o Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-revan:latest

      - name: Deploy na VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 72.60.14.233
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Instalar Docker se não existir
            if ! command -v docker &> /dev/null; then
              apt update
              apt install -y docker.io
            fi

            # Instalar Docker Compose plugin se não existir
            if ! docker compose version &> /dev/null; then
              mkdir -p /usr/local/lib/docker/cli-plugins
              curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
                -o /usr/local/lib/docker/cli-plugins/docker-compose
              chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
            fi

            # Criar pasta do projeto
            mkdir -p /app/backend-revan
            cd /app/backend-revan

            # Baixar docker-compose.yml do Google Drive (link direto)
            curl -L "https://drive.google.com/uc?export=download&id=1pPy1Gv0afyK-UKB2n3ag9-YeKyKtzVHt" -o docker-compose.yml

            # Subir containers com nova imagem
            docker compose pull
            docker compose up -d
